name: school_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.2
  loading_indicator: ^3.1.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.0+1
  firebase_storage: ^11.6.11
  syncfusion_flutter_pdfviewer: ^25.1.42
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.5
  google_sign_in: ^6.2.1
  google_fonts: 6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/app/
    - assets/images/app/icons/
